pipeline {
  agent any

  environment {
    DOCKER_HUB_CREDENTIALS = 'docker-hub-credentials'
    DOCKER_IMAGE_NAME = 'easybus-front'
    DOCKER_REGISTRY_URL = 'docker.io'
    DOCKER_IMAGE_TAG = 'latest'
  }

  stages {
    stage('Build Docker image') {
      steps {
        script {
          docker.withRegistry(DOCKER_REGISTRY_URL, DOCKER_HUB_CREDENTIALS) {
            def dockerImage = docker.build("${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}", "-f Dockerfile .")
            dockerImage.push()
          }
        }
      }
    }
  }
}