spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easybus
    username: kamal
    password: kamal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      password: jjjj

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

server:
  port: 8081

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

paypal:
  clientId: AZhgu21wrutKMxvWQNyEDvYym9sf-W3Pn9BWQQeop-JE8s-u9Gw21AkW6wHLXNXEAMzEvyEpt7bfRqoy
  clientSecret: EEHyiMhB29HbRokijhrO9YrVsyvOhodyhwsDU_mXx3cMHK_ILHIPr5vGsK_iOZCfjdBeiX6hBLwKz3-S