spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easybus
    username: kamal
    password: kamal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      password: jjjj
  #mail:
  #  host: smtp.googlemail.com
  #  port: 587
  #  username: kamal.ezzarmou1@gmail.com
  #  password:
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

server:
  port: 8081

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

paypal:
  clientId:
  clientSecret:

#swagger config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
