pipeline {
    agent any 
    stages {
        stage('Build jar') {
            steps {
                sh '../docker-compose run -d --name easybus-db db'
                sh 'mvn clean install -DskipTests' 
            }
        }
        stage('Build docker image'){
            steps {
                sh 'docker build -t easybus:latest .'
            }
        }
        /*stage('Tag image'){
            steps {
                sh 'docker tag easybus kamalezzarmrou/easybus_backend'
            }
        }
        stage('Push image'){
            steps {
                sh 'docker push kamalezzarmrou/easybus_backend'
            }
        }*/
    }
}