pipeline {
  agent any

  environment {
    DOCKER_HUB_CREDENTIALS = 'docker-hub-credentials'
    DOCKER_IMAGE_NAME = 'my-maven-app'
    DOCKER_REGISTRY_URL = 'docker.io'
    DOCKER_IMAGE_TAG = 'latest'
  }

  stages {
    stage('Build Maven project') {
    agent {
        docker {
             image 'maven:3.9.3-eclipse-temurin-17'
             args '-v $HOME/.m2:/root/.m2'
        }
    }
      steps {
        sh '../docker-compose run -d --name easybus-db db'
        sh 'mvn clean package -DskipTests'
      }
    }

    stage('Build Docker image') {
      steps {
        script {
          docker.withRegistry(DOCKER_REGISTRY_URL, DOCKER_HUB_CREDENTIALS) {
            def dockerImage = docker.build("${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}", ".")
            dockerImage.push()
          }
        }
      }
    }


  }
}
